# Generated by Django 5.2.1 on 2025-07-23 16:38

import base_upload.models.uploaded_file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(db_index=True, help_text='Application that this file belongs to.', max_length=15, verbose_name='Application Code')),
                ('owner', models.CharField(blank=True, help_text='This holds username of the user that uploaded the file, which could be a provisional email address', max_length=128, null=True)),
                ('content_type', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.BinaryField()),
                ('s3_path', models.CharField(default='Unnamed', help_text='Full S3 file path', max_length=256)),
                ('basename', models.CharField(db_index=True, default='Unnamed', help_text='File name without the path info', max_length=128)),
                ('original_name', models.CharField(help_text='Name of file as uploaded by user', max_length=128)),
                ('tag', models.CharField(blank=True, help_text='Any sort of tag that will be useful for looking up files', max_length=30, null=True)),
                ('foreign_table', models.CharField(blank=True, db_index=True, default=None, help_text='table or model that this file belongs to', max_length=100, null=True)),
                ('foreign_key', models.IntegerField(blank=True, db_index=True, default=None, help_text='ID of a record in another table that this file belongs to', null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Allow flags for Deleted, Archived, or maybe someday Scanned (for viruses)', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(db_index=True, help_text='Application that this file belongs to.', max_length=15, verbose_name='Application Code')),
                ('owner', models.CharField(blank=True, help_text='This holds username of the user that uploaded the file, which could be a provisional email address', max_length=128, null=True)),
                ('content_type', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=base_upload.models.uploaded_file.get_upload_path)),
                ('s3_path', models.CharField(help_text='Full S3 file path', max_length=256)),
                ('basename', models.CharField(db_index=True, help_text='File name without the path info', max_length=128)),
                ('original_name', models.CharField(help_text='Name of file as uploaded by user', max_length=128)),
                ('tag', models.CharField(blank=True, help_text='Any sort of tag that will be useful for looking up files', max_length=30, null=True)),
                ('foreign_table', models.CharField(blank=True, db_index=True, default=None, help_text='table or model that this file belongs to', max_length=100, null=True)),
                ('foreign_key', models.IntegerField(blank=True, db_index=True, default=None, help_text='ID of a record in another table that this file belongs to', null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Allow flags for Deleted, Archived, or maybe someday Scanned (for viruses)', max_length=1, null=True)),
            ],
        ),
    ]
