# Generated by Django 5.2.1 on 2025-10-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasefile',
            old_name='s3_path',
            new_name='fs_path',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='s3_path',
            new_name='fs_path',
        ),
    ]
