# Generated by Django 5.2.1 on 2025-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=80)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('transfers_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
