# Generated by Django 5.2.1 on 2025-10-09 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=80)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('transfers_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('card_payments_enabled', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('event_id', models.CharField(max_length=60)),
                ('object_type', models.CharField(db_index=True, max_length=60)),
                ('object_id', models.CharField(db_index=True, max_length=60)),
                ('refreshed', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('email', models.CharField(db_index=True, max_length=180, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('use_auto_pay', models.BooleanField(default=False)),
                ('balance_cents', models.IntegerField(default=0)),
                ('delinquent', models.BooleanField(default=False)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('default_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('default_source', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=20, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='base_stripe.stripecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('related_type', models.CharField(blank=True, max_length=20, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base_stripe.stripecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('related_type', models.CharField(blank=True, max_length=20, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('hosted_invoice_url', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='base_stripe.stripecustomer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='base_stripe.stripesubscription')),
            ],
        ),
    ]
