# Generated by Django 5.2.1 on 2025-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccount',
            name='stripe_id',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
