# Generated by Django 5.2.1 on 2025-10-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0002_stripeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('active', models.BooleanField(db_index=True)),
                ('nickname', models.CharField(blank=True, max_length=80, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('recurring', models.JSONField(blank=True, default=dict, null=True)),
                ('type', models.CharField(blank=True, max_length=12, null=True)),
                ('unit_amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base_stripe.stripeproduct')),
            ],
        ),
    ]
