# Generated by Django 5.2.1 on 2025-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0002_alter_connectedaccount_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='card_payments_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
