# Generated by Django 5.2.1 on 2025-08-05 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0003_connectedaccount_card_payments_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('email', models.CharField(db_index=True, max_length=180, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('balance_cents', models.IntegerField(default=0)),
                ('delinquent', models.BooleanField(default=False)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
