# Generated by Django 5.2.1 on 2025-10-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0003_stripeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
