# Generated by Django 5.2.1 on 2025-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0004_stripeprice_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='badge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
