# Generated by Django 5.2.1 on 2025-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0004_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('event_id', models.CharField(max_length=60)),
                ('object_type', models.CharField(db_index=True, max_length=60)),
                ('object_id', models.CharField(db_index=True, max_length=60)),
            ],
        ),
    ]
