# Generated by Django 5.2.1 on 2025-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0005_stripeprice_badge_stripeprice_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
