# Generated by Django 5.2.1 on 2025-10-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0006_alter_stripecheckoutsession_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='email',
            field=models.CharField(db_index=True, max_length=180),
        ),
    ]
