# Generated by Django 5.2.1 on 2025-08-07 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0006_alter_stripecustomer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeCustomer',
            new_name='Customer',
        ),
    ]
