# Generated by Django 5.2.1 on 2025-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0007_rename_stripecustomer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='use_auto_pay',
            field=models.BooleanField(default=False),
        ),
    ]
