# Generated by Django 5.2.1 on 2025-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0007_alter_stripecustomer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
