# Generated by Django 5.2.1 on 2025-08-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0008_customer_use_auto_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('related_type', models.CharField(max_length=20)),
                ('related_id', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base_stripe.customer')),
            ],
        ),
    ]
