# Generated by Django 5.2.1 on 2025-10-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0008_stripecheckoutsession_deleted_stripecustomer_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectedaccount',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
