# Generated by Django 5.2.1 on 2025-10-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0009_stripeconnectedaccount_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='base_stripe.stripeconnectedaccount'),
        ),
    ]
