# Generated by Django 5.2.1 on 2025-08-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='refreshed',
            field=models.BooleanField(default=False),
        ),
    ]
