# Generated by Django 5.2.1 on 2025-08-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0010_webhookevent_refreshed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('related_type', models.CharField(max_length=20)),
                ('related_id', models.IntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='base_stripe.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='base_stripe.subscription')),
            ],
        ),
    ]
