# Generated by Django 5.2.1 on 2025-10-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0010_stripecustomer_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base_stripe.stripeconnectedaccount'),
        ),
    ]
