# Generated by Django 5.2.1 on 2025-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0011_stripeproduct_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookevent',
            name='account_id',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
