# Generated by Django 5.2.1 on 2025-10-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0012_stripewebhookevent_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='base_stripe.stripeconnectedaccount'),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base_stripe.stripeconnectedaccount'),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base_stripe.stripeconnectedaccount'),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='base_stripe.stripeconnectedaccount'),
        ),
    ]
