# Generated by Django 5.2.1 on 2025-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0013_stripecheckoutsession_stripe_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeconnectedaccount',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
