# Generated by Django 5.2.1 on 2025-08-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0013_remove_invoice_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='related_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
