# Generated by Django 5.2.1 on 2025-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0014_alter_stripeconnectedaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
