# Generated by Django 5.2.1 on 2025-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0014_alter_subscription_related_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
