# Generated by Django 5.2.1 on 2025-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0015_stripesubscription_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='payment_expire_ym',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
