# Generated by Django 5.2.1 on 2025-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0015_alter_invoice_related_id_alter_invoice_related_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
