# Generated by Django 5.2.1 on 2025-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0016_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
