# Generated by Django 5.2.1 on 2025-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0016_stripesubscription_payment_expire_ym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='payment_expire_ym',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
