# Generated by Django 5.2.1 on 2025-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0017_invoice_amount_charged_invoice_amount_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='metadata',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
