# Generated by Django 5.2.1 on 2025-09-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0021_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='base_stripe.subscription'),
        ),
    ]
