# Generated by Django 5.2.1 on 2025-09-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0022_invoice_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
    ]
