# Generated by Django 5.2.1 on 2025-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0023_delete_subscriptioninvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
