# Generated by Django 5.2.1 on 2025-09-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0024_subscription_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
