# Generated by Django 5.2.1 on 2025-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0025_customer_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
