# Generated by Django 5.2.1 on 2025-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0026_invoice_period_end_invoice_period_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
