# Generated by Django 5.2.1 on 2025-10-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0027_invoice_hosted_invoice_url_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('metadata', models.CharField(blank=True, max_length=500, null=True)),
                ('related_type', models.CharField(blank=True, max_length=20, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='base_stripe.customer')),
            ],
        ),
    ]
