# Generated by Django 5.2.1 on 2025-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0028_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='url',
            field=models.CharField(default='localhost', max_length=150),
            preserve_default=False,
        ),
    ]
