# Generated by Django 5.2.1 on 2025-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0029_checkoutsession_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
