# Generated by Django 5.2.1 on 2025-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0030_alter_checkoutsession_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
