# Generated by Django 5.2.1 on 2025-10-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0031_checkoutsession_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
