# Generated by Django 5.2.1 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0032_webhookevent_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
