# Generated by Django 5.2.1 on 2025-10-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0033_alter_subscription_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
