# Generated by Django 5.2.1 on 2025-10-09 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(blank=True, default=None, help_text='Group features to toggle an entire set of features together', max_length=80, null=True, verbose_name='Group Code')),
                ('feature_code', models.CharField(help_text='Short identifier for referencing this feature from source code', max_length=30, verbose_name='Feature Identifier')),
                ('feature_title', models.CharField(help_text='Title of the feature (displayed to users)', max_length=80, verbose_name='Feature Title')),
                ('feature_description', models.CharField(blank=True, default=None, help_text='Optional description of the feature (displayed to users)', max_length=500, null=True, verbose_name='Feature Description')),
                ('status', models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('L', 'Limited to Admins')], default='L', help_text='Is this feature active?', max_length=1)),
                ('enable_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('disable_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XssAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this attempt was made in.', max_length=15, verbose_name='Application Code')),
                ('user_username', models.CharField(blank=True, max_length=30, null=True)),
                ('reviewer_username', models.CharField(blank=True, max_length=30, null=True)),
                ('path', models.CharField(help_text='Request path', max_length=200)),
                ('parameter_name', models.CharField(blank=True, default=None, help_text='Parameter name', max_length=80, null=True)),
                ('parameter_value', models.CharField(blank=True, default=None, help_text='Parameter content', max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, default=None, help_text='Session Key', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this action was taken in.', max_length=15, verbose_name='Application Code')),
                ('crud_code', models.CharField(db_index=True, max_length=1)),
                ('event_code', models.CharField(db_index=True, help_text='This string should identify the type of event', max_length=80)),
                ('reference_code', models.CharField(blank=True, db_index=True, default=None, max_length=60, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('previous_value', models.CharField(blank=True, default=None, help_text='Value before change was made', max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, default=None, help_text='Value after change was made', max_length=500, null=True)),
                ('comments', models.TextField(blank=True, default=None, help_text='Comments about the event', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('impersonated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated', to=settings.AUTH_USER_MODEL)),
                ('proxied_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxied', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(db_index=True, max_length=60)),
                ('email', models.CharField(db_index=True, max_length=150, unique=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('atype', models.CharField(max_length=1)),
                ('street_1', models.CharField(max_length=80)),
                ('street_2', models.CharField(blank=True, max_length=80, null=True)),
                ('street_3', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=15)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='base.contact')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.CharField(db_index=True, default='N', max_length=1)),
                ('request_type_code', models.CharField(default='F', max_length=1)),
                ('summary', models.CharField(max_length=120)),
                ('detail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=128)),
                ('parameters', models.CharField(blank=True, max_length=500, null=True)),
                ('code_detail', models.CharField(blank=True, help_text='file, function, and line number of error', max_length=128, null=True)),
                ('auth_description', models.CharField(max_length=80)),
                ('status_code', models.CharField(default='N', max_length=1)),
                ('error_friendly', models.CharField(blank=True, help_text='Error that the user saw', max_length=128, null=True)),
                ('error_system', models.CharField(blank=True, help_text='Actual system error', max_length=128, null=True)),
                ('debug_info', models.CharField(blank=True, help_text='Additional debug info', max_length=128, null=True)),
                ('stacktrace', models.TextField(blank=True, help_text='StackTrace', null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser info', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='base.authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ptype', models.CharField(max_length=1)),
                ('preferred', models.CharField(default='N', max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='base.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('status_code', models.CharField(default='A', max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reward_type_code', models.CharField(default='C', max_length=1)),
                ('reward_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reward_cap', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reward_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('reward_expiration_days', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('data_type', models.CharField(max_length=10)),
                ('current_value', models.CharField(blank=True, max_length=80, null=True)),
                ('previous_value', models.CharField(blank=True, max_length=80, null=True)),
                ('version', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnhancementVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('enhancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='base.enhancementrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enhancement', 'user')},
            },
        ),
    ]
