# Generated by Django 5.2.1 on 2025-06-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=128)),
                ('parameters', models.CharField(blank=True, max_length=500, null=True)),
                ('code_detail', models.CharField(blank=True, help_text='file, function, and line number of error', max_length=128, null=True)),
                ('auth_description', models.CharField(max_length=80)),
                ('status_code', models.CharField(default='N', max_length=1)),
                ('error_friendly', models.CharField(blank=True, help_text='Error that the user saw', max_length=128, null=True)),
                ('error_system', models.CharField(blank=True, help_text='Actual system error', max_length=128, null=True)),
                ('debug_info', models.CharField(blank=True, help_text='Additional debug info', max_length=128, null=True)),
                ('stacktrace', models.TextField(blank=True, help_text='StackTrace', null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser info', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
