# Generated by Django 5.2.1 on 2025-05-30 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this action was taken in.', max_length=15, verbose_name='Application Code')),
                ('impersonated_username', models.CharField(blank=True, max_length=30, null=True)),
                ('proxied_username', models.CharField(blank=True, max_length=30, null=True)),
                ('crud_code', models.CharField(db_index=True, max_length=1)),
                ('event_code', models.CharField(db_index=True, help_text='This string should identify the type of event', max_length=80)),
                ('reference_code', models.CharField(blank=True, db_index=True, default=None, max_length=60, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('previous_value', models.CharField(blank=True, default=None, help_text='Value before change was made', max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, default=None, help_text='Value after change was made', max_length=500, null=True)),
                ('comments', models.TextField(blank=True, default=None, help_text='Comments about the event', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
