# Generated by Django 5.2.1 on 2025-05-30 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='impersonated_username',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='proxied_username',
        ),
        migrations.AddField(
            model_name='audit',
            name='impersonated_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit',
            name='proxied_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxied', to=settings.AUTH_USER_MODEL),
        ),
    ]
