# Generated by Django 5.2.1 on 2025-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_audit_impersonated_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xssattempt',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='xssattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='xssattempt',
            name='reviewer_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='xssattempt',
            name='user_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
