# Generated by Django 5.2.1 on 2025-06-26 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_enhancementrequest_request_type_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enhancementvote',
            unique_together={('enhancement', 'user')},
        ),
    ]
