# Generated by Django 5.2.1 on 2025-06-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_xssattempt_reviewer_remove_xssattempt_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('status_code', models.CharField(default='A', max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reward_type_code', models.CharField(default='C', max_length=1)),
                ('reward_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reward_cap', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reward_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('reward_expiration_days', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
