# Generated by Django 5.2.1 on 2025-06-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='app_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='App Code'),
        ),
    ]
