# Generated by Django 5.2.1 on 2025-06-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=200)),
                ('identifier', models.CharField(db_index=True, max_length=6, unique=True)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=3)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('info_email', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('status_code', models.CharField(default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AirportManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(default='A', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='the_hangar_hub.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('default_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='the_hangar_hub.airport')),
            ],
            options={
                'unique_together': {('airport', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Hangar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=1)),
                ('electric', models.BooleanField(default=False)),
                ('default_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangars', to='the_hangar_hub.building')),
            ],
            options={
                'unique_together': {('building', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HangarApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(default='N', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('preferred_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('hangar_type_code', models.CharField(default='F', max_length=1, verbose_name='Hangar Type')),
                ('aircraft_type_code', models.CharField(default='A', max_length=2, verbose_name='Aircraft Type')),
                ('aircraft_make', models.CharField(blank=True, max_length=30, null=True, verbose_name='Aircraft Make')),
                ('aircraft_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Aircraft Model')),
                ('aircraft_wingspan', models.IntegerField(blank=True, null=True, verbose_name='Wingspan')),
                ('aircraft_height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registration Number')),
                ('applicant_notes', models.TextField(blank=True, null=True, verbose_name='Applicant Notes')),
                ('manager_notes_public', models.TextField(blank=True, null=True, verbose_name='Manager Notes')),
                ('manager_notes_private', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fee_status', models.CharField(blank=True, max_length=1, null=True)),
                ('fee_payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('fee_notes', models.TextField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='the_hangar_hub.airport')),
                ('mailing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.address', verbose_name='Address')),
                ('preferred_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.phone', verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HangarApplicationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('required_fields_csv', models.TextField(blank=True, null=True)),
                ('ignored_fields_csv', models.TextField(blank=True, null=True)),
                ('infotext_top', models.TextField(blank=True, null=True)),
                ('infotext_personal', models.TextField(blank=True, null=True)),
                ('infotext_aircraft', models.TextField(blank=True, null=True)),
                ('infotext_hangar', models.TextField(blank=True, null=True)),
                ('infotext_bottom', models.TextField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_prefs', to='the_hangar_hub.airport', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HangarOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(default='A', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='the_hangar_hub.hangar')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='base.contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='the_hangar_hub.hangar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='the_hangar_hub.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(db_index=True, max_length=128)),
                ('verification_code', models.CharField(max_length=30)),
                ('role_code', models.CharField(max_length=8)),
                ('status_code', models.CharField(default='I', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='the_hangar_hub.airport')),
                ('hangar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='the_hangar_hub.hangar')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_invited', to=settings.AUTH_USER_MODEL)),
                ('resulting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='the_hangar_hub.tenant')),
            ],
        ),
    ]
