# Generated by Django 5.2.1 on 2025-10-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='series',
            field=models.CharField(db_index=True, default='default', max_length=6),
            preserve_default=False,
        ),
    ]
