# Generated by Django 5.2.1 on 2025-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='info_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
