# Generated by Django 5.2.1 on 2025-09-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='prior_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_hangar_hub.rentalagreement'),
        ),
    ]
