# Generated by Django 5.2.1 on 2025-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplication',
            name='wl_group_code',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='hangarapplication',
            name='wl_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
