# Generated by Django 5.2.1 on 2025-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='status_code',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
