# Generated by Django 5.2.1 on 2025-06-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportmanager',
            old_name='status',
            new_name='status_code',
        ),
    ]
