# Generated by Django 5.2.1 on 2025-06-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0002_alter_airport_info_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='A', max_length=1)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='the_hangar_hub.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
