# Generated by Django 5.2.1 on 2025-09-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0002_rentalagreement_prior_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinvoice',
            name='payment_method_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
