# Generated by Django 5.2.1 on 2025-06-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0002_airport_referral_code_airport_status_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='role',
            new_name='role_code',
        ),
    ]
