# Generated by Django 5.2.1 on 2025-10-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('base_stripe', '0007_alter_stripecustomer_email'),
        ('the_hangar_hub', '0002_alter_hangarapplicationpreferences_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='customer',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='base_stripe.stripecustomer'),
        ),
        migrations.CreateModel(
            name='AirportCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='the_hangar_hub.airport')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='base.contact')),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_customers', to='base_stripe.stripecustomer')),
            ],
        ),
    ]
