# Generated by Django 5.2.1 on 2025-10-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0003_remove_tenant_customer_rentalagreement_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='url',
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='the_hangar_hub.airport')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='the_hangar_hub.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('contact_frequencies', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=200, null=True)),
                ('hours_m', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_t', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_w', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_r', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_f', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_s', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_u', models.CharField(blank=True, max_length=25, null=True)),
                ('avgas_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('jeta_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mogas_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airport_logos/')),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customized_content', to='the_hangar_hub.airport')),
            ],
        ),
    ]
