# Generated by Django 5.2.1 on 2025-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0003_rename_role_invitation_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplication',
            name='aircraft_type_code',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
