# Generated by Django 5.2.1 on 2025-09-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0015_alter_invoice_related_id_alter_invoice_related_type'),
        ('the_hangar_hub', '0003_rentalinvoice_payment_method_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinvoice',
            name='stripe_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_invoices', to='base_stripe.subscription'),
        ),
    ]
