# Generated by Django 5.2.1 on 2025-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
