# Generated by Django 5.2.1 on 2025-07-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0003_maintenancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('visibility_code', models.CharField(default='I', max_length=1)),
                ('mx_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_comments', to='the_hangar_hub.maintenancerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
