# Generated by Django 5.2.1 on 2025-10-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0004_amenity_remove_airport_url_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizedcontent',
            old_name='contact_frequencies',
            new_name='frequencies',
        ),
    ]
