# Generated by Django 5.2.1 on 2025-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0004_maintenancecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
