# Generated by Django 5.2.1 on 2025-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0004_rentalinvoice_stripe_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinvoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
