# Generated by Django 5.2.1 on 2025-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0004_hangarapplication_aircraft_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
