# Generated by Django 5.2.1 on 2025-06-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_feature_app_code_variable'),
        ('the_hangar_hub', '0005_airport_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplication',
            name='mailing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.address'),
        ),
        migrations.AddField(
            model_name='hangarapplication',
            name='preferred_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hangarapplication',
            name='preferred_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.phone'),
        ),
    ]
