# Generated by Django 5.2.1 on 2025-07-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0005_airport_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='billing_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_street_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_street_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
