# Generated by Django 5.2.1 on 2025-10-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0005_rename_contact_frequencies_customizedcontent_frequencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenity',
            name='proposed_by_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_amenities', to='the_hangar_hub.airport'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='proposed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_amenities', to=settings.AUTH_USER_MODEL),
        ),
    ]
