# Generated by Django 5.2.1 on 2025-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0005_building_hangar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='default_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hangar',
            name='default_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hangar',
            name='electric',
            field=models.BooleanField(default=False),
        ),
    ]
