# Generated by Django 5.2.1 on 2025-09-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0005_rentalinvoice_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='stripe_tx_fee',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
        ),
    ]
