# Generated by Django 5.2.1 on 2025-06-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0006_alter_building_default_rent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('airport', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='hangar',
            unique_together={('building', 'code')},
        ),
    ]
