# Generated by Django 5.2.1 on 2025-10-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0006_amenity_approved_amenity_proposed_by_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
