# Generated by Django 5.2.1 on 2025-06-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0006_hangarapplication_mailing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangarApplicationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('required_fields_csv', models.TextField()),
                ('ignored_fields_csv', models.TextField()),
                ('infotext_top', models.TextField()),
                ('infotext_personal', models.TextField()),
                ('infotext_aircraft', models.TextField()),
                ('infotext_hangar', models.TextField()),
                ('infotext_bottom', models.TextField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_preferences', to='the_hangar_hub.airport')),
            ],
        ),
    ]
