# Generated by Django 5.2.1 on 2025-09-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0006_airport_stripe_tx_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinvoice',
            name='stripe_invoice',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rentalinvoice',
            name='stripe_subscription',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
