# Generated by Django 5.2.1 on 2025-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0006_airport_billing_city_airport_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='subscription_lookup_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
