# Generated by Django 5.2.1 on 2025-09-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0007_alter_rentalinvoice_stripe_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalinvoice',
            old_name='stripe_invoice',
            new_name='stripe_invoice_id',
        ),
        migrations.RenameField(
            model_name='rentalinvoice',
            old_name='stripe_subscription',
            new_name='stripe_subscription_id',
        ),
    ]
