# Generated by Django 5.2.1 on 2025-07-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0007_airport_subscription_lookup_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='subscription_lookup_key',
            new_name='subscription_id',
        ),
    ]
