# Generated by Django 5.2.1 on 2025-10-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0007_alter_amenity_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'ordering': ['amenity__title']},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='customizedcontent',
            name='after_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
