# Generated by Django 5.2.1 on 2025-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0008_rename_stripe_invoice_rentalinvoice_stripe_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinvoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
    ]
