# Generated by Django 5.2.1 on 2025-06-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0008_tenant_invitation_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hangar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='status',
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='the_hangar_hub.hangar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='the_hangar_hub.tenant')),
            ],
        ),
    ]
