# Generated by Django 5.2.1 on 2025-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0008_alter_amenities_options_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='sort_modifier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
