# Generated by Django 5.2.1 on 2025-06-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0008_alter_hangarapplicationpreferences_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_prefs', to='the_hangar_hub.airport', unique=True),
        ),
    ]
