# Generated by Django 5.2.1 on 2025-07-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0008_rename_subscription_lookup_key_airport_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('affected_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='the_hangar_hub.building')),
                ('affected_hangar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='the_hangar_hub.hangar')),
                ('tenant_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='the_hangar_hub.maintenancerequest')),
            ],
        ),
    ]
