# Generated by Django 5.2.1 on 2025-10-23 02:11

import django.db.models.deletion
import the_hangar_hub.models.airport
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0009_amenity_sort_modifier_alter_amenity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=the_hangar_hub.models.airport.blog_image_upload_to)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_entries', to='the_hangar_hub.airport')),
            ],
        ),
    ]
