# Generated by Django 5.2.1 on 2025-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0009_alter_rentalinvoice_stripe_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinvoice',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
