# Generated by Django 5.2.1 on 2025-06-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_feature_app_code_variable'),
        ('the_hangar_hub', '0009_alter_hangarapplicationpreferences_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangarapplication',
            name='aircraft_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='aircraft_make',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aircraft Make'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='aircraft_model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aircraft Model'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='aircraft_type_code',
            field=models.CharField(default='A', max_length=2, verbose_name='Aircraft Type'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='aircraft_wingspan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wingspan'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='hangar_type_code',
            field=models.CharField(default='F', max_length=1, verbose_name='Hangar Type'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='mailing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='plane_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='preferred_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='preferred_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.phone', verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='ignored_fields_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='infotext_aircraft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='infotext_bottom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='infotext_hangar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='infotext_personal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='infotext_top',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplicationpreferences',
            name='required_fields_csv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
