# Generated by Django 5.2.1 on 2025-06-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0009_remove_tenant_account_status_remove_tenant_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hangar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='the_hangar_hub.hangar'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
