# Generated by Django 5.2.1 on 2025-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0009_scheduledmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='summary',
            field=models.CharField(default='Mx', max_length=120),
            preserve_default=False,
        ),
    ]
