# Generated by Django 5.2.1 on 2025-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0010_scheduledmaintenance_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='status_code',
            field=models.CharField(db_index=True, default='S', max_length=1),
        ),
    ]
