# Generated by Django 5.2.1 on 2025-09-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0015_alter_invoice_related_id_alter_invoice_related_type'),
        ('the_hangar_hub', '0010_rentalinvoice_stripe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalinvoice',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='rentalinvoice',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='stripe_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_invoices', to='base_stripe.invoice'),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='stripe_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_invoices', to='base_stripe.subscription'),
        ),
    ]
