# Generated by Django 5.2.1 on 2025-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0010_blogentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='image',
        ),
    ]
