# Generated by Django 5.2.1 on 2025-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0010_alter_hangarapplication_aircraft_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplication',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
