# Generated by Django 5.2.1 on 2025-06-13 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0010_invitation_hangar_alter_rental_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HangarApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(default='N', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('hangar_type_code', models.CharField(default='F', max_length=1)),
                ('aircraft_make', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_model', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_wingspan', models.IntegerField(blank=True, null=True)),
                ('aircraft_height', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('plane_notes', models.TextField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fee_status', models.CharField(blank=True, max_length=1, null=True)),
                ('fee_payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('fee_notes', models.TextField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='the_hangar_hub.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HangarOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(default='A', max_length=1)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='the_hangar_hub.hangar')),
            ],
        ),
    ]
