# Generated by Django 5.2.1 on 2025-09-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0011_remove_rentalinvoice_stripe_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalinvoice',
            name='stripe_status',
        ),
    ]
