# Generated by Django 5.2.1 on 2025-10-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0011_remove_blogentry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='info_email',
            new_name='support_email',
        ),
    ]
