# Generated by Django 5.2.1 on 2025-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0011_scheduledmaintenance_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='application_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hangarapplication',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Application Fee'),
        ),
    ]
