# Generated by Django 5.2.1 on 2025-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0012_airport_application_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
