# Generated by Django 5.2.1 on 2025-09-11 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0017_invoice_amount_charged_invoice_amount_remaining'),
        ('the_hangar_hub', '0012_remove_rentalinvoice_stripe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalagreement',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='stripe_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='base_stripe.subscription'),
        ),
    ]
