# Generated by Django 5.2.1 on 2025-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0012_alter_blogentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='support_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
