# Generated by Django 5.2.1 on 2025-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0013_airport_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangar',
            name='auto_door',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hangar',
            name='heated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hangar',
            name='shelves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hangar',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hangar',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
