# Generated by Django 5.2.1 on 2025-09-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0018_customer_metadata_invoice_metadata_and_more'),
        ('the_hangar_hub', '0013_remove_rentalagreement_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='future_stripe_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_rental_agreements', to='base_stripe.subscription'),
        ),
    ]
