# Generated by Django 5.2.1 on 2025-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0013_airport_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
