# Generated by Django 5.2.1 on 2025-09-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stripe', '0024_subscription_trial_end_date'),
        ('the_hangar_hub', '0014_rentalagreement_future_stripe_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='base_stripe.customer'),
        ),
    ]
