# Generated by Django 5.2.1 on 2025-11-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0014_hangar_auto_door_hangar_heated_hangar_shelves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplicationpreferences',
            name='infotext_certification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
