# Generated by Django 5.2.1 on 2025-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0015_hangarapplicationpreferences_infotext_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangarapplication',
            name='certification_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
