# Generated by Django 5.2.1 on 2025-09-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0015_alter_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='stripe_customer_id',
            new_name='customer',
        ),
    ]
