# Generated by Django 5.2.1 on 2025-09-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0016_rename_stripe_customer_id_tenant_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='the_hangar_hub.airport'),
        ),
    ]
