# Generated by Django 5.2.1 on 2025-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0016_hangarapplication_certification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangar',
            name='type_code',
            field=models.CharField(default='TH', max_length=2),
        ),
    ]
