# Generated by Django 5.2.1 on 2025-11-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0017_hangar_type_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangar',
            old_name='type_code',
            new_name='hangar_type_code',
        ),
    ]
