# Generated by Django 5.2.1 on 2025-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0019_messageboardthread_messageboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboardentry',
            name='role_display',
            field=models.CharField(default='?', max_length=30),
            preserve_default=False,
        ),
    ]
