# Generated by Django 5.2.1 on 2025-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0020_messageboardentry_role_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageboardentry',
            old_name='visibility_ind',
            new_name='visibility_code',
        ),
        migrations.RemoveField(
            model_name='messageboardentry',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='messageboardthread',
            name='tenant',
        ),
        migrations.AddField(
            model_name='messageboardentry',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageboardentry',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
