# Generated by Django 5.2.1 on 2025-11-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0021_rename_visibility_ind_messageboardentry_visibility_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboardentry',
            name='in_response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='the_hangar_hub.messageboardentry'),
        ),
    ]
