# Generated by Django 5.2.1 on 2025-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hangar_hub', '0022_alter_messageboardentry_in_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboardentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
