# Generated by Django 5.2.1 on 2025-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infotext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this text belongs to', max_length=15, verbose_name='Application Code')),
                ('text_code', models.CharField(help_text='Unique identifier for this text instance', max_length=256, verbose_name='Text Identifier')),
                ('user_edited', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', help_text='Has this text been modified from its coded value?', max_length=1)),
                ('content', models.TextField(verbose_name='Text Content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
